### ISSUE TITLE
EC2 instances with multiple network interfaces do not get their ip and mac address fields rendered correctly

### ISSUE THREAD

**Issue by barrettnet** [ZachChristensen28/SA-AwsAssets#20]
**Describe the bug**
EC2 instances with multiple network interfaces do not get their ip and mac address fields rendered correctly in that they are treated as mv fields rather than a pipe-concatenated string.

**Expected behavior**
According to https://docs.splunk.com/Documentation/ES/latest/Admin/Formatassetoridentitylist, if an asset has multiple IP addresses, these should be separated by a pipe character.  Ditto for multiple MAC addresses.

**Versions (please complete the following information):**
 - SA-AwsAssets Version (This add-on): 1.0.2

**Additional context**
I believe that the fix is to simply add the following after the call to iplocate:
```
| eval ip = mvjoin(ip,"|")
| eval mac = mvjoin(mac,"|")
```
It should be noted that the call to iplocation will also fail if there are multiple interfaces.  I'm not sure how to handle it, other than simply using the first interface perhaps.

**Comment by ZachChristensen28** [comment]
Thank you for reporting this. I will be using a similar approach to the one you proposed. 

### Old

```
| rename NetworkInterfaces{}.MacAddress as mac, NetworkInterfaces{}.PrivateIpAddress as IP 
```

### New

```
| eval
mac=mvjoin('NetworkInterfaces{}.MacAddress', "|"),
ip=mvjoin('NetworkInterfaces{}.PrivateIpAddress', "|")
```

Thankfully, this will not affect the `iplocation` command since that is using the public IP field `NetworkInterfaces{}.Association.PublicIp` and not the one we use for the private IP. 

To that point, do you have any instances that are assigned multiple different external IPs for this field (`NetworkInterfaces{}.Association.PublicIp`)?

**Comment by barrettnet** [comment]
Hi Zack, 

Yes, there are instances with multiple (and different) external IPs via the NetworkInterfaces{}.Association.PublicIp field.  In each case, one is owned by "amazon" (NetworkInterfaces{}.Association.IpOwnerId ="amazon") and the other is owned by the account_id value (NetworkInterfaces{}.Association.IpOwnerId = &lt;account ID number&gt; = account_id).

**Comment by barrettnet** [comment]
Regarding the iplocation issue and how it would work with an instance with multiple network interfaces with public IPs, I have been experimenting with the following and it seems to be working:

### Old
`| iplocation NetworkInterfaces{}.Association.PublicIp`

### New
```
| eval publicIp = case(
  mvindex('NetworkInterfaces{}.Association.PublicIp',0)=OwnerId, mvindex('NetworkInterfaces{}.Association.PublicIp',0),
  mvindex('NetworkInterfaces{}.Association.PublicIp',1)=OwnerId, mvindex('NetworkInterfaces{}.Association.PublicIp',1),
  true(),null())
| iplocation publicIp
| fields - publicIp
```
As written, it'll only support an instance with a maximum of two instances so there may be merit in adding a few more entries "to be safe".

**Comment by barrettnet** [comment]
Oops, yes, a transcription error on my part.

And yes, the PublicIp's of the instances with two interfaces enrich with the same location data so it looks like simply using the first interface for the iplocation of the host/instance is viable.

**Comment by ZachChristensen28** [comment]
@barrettnet this is the updated search to fix the multiple IP issues (private/public). Will you give it a try and see if it works for you?

```
index=<your aws index> eventtype="aws_metadata_ec2_instances"
| dedup InstanceId
| eval
    public_ip=mvjoin('NetworkInterfaces{}.Association.PublicIp', ","),
    pub_ip_loc=mvindex('NetworkInterfaces{}.Association.PublicIp', 0),
    category=mvjoin(lower(mvsort(mvappend(
    "gen: sa-aws-assets",
    "hypervisor: ".Hypervisor,
    "image_id: ".ImageId,
    "instance_type: ".InstanceType,
    "launch_time: ".strftime(strptime(LaunchTime,"%FT%T.%3Q%Z"), "%x %T %Z"),
    "monitoring: ".'Monitoring.State',
    "public_ip: ".public_ip,
    "group_id: ".'SecurityGroups{}.GroupId',
    "group_name: ".'SecurityGroups{}.GroupName',
    "subnet_id: ".'NetworkInterfaces{}.SubnetId',
    "vpc_id: ".'NetworkInterfaces{}.VpcId',
    "availability_zone: ".'Placement.AvailabilityZone',
    "region: ".Region,
    "os_platform: ".PlatformDetails,
    "state: ".'State.Name',
    "tags: ".mvjoin(custom_tag, ", "),
    "enabled: ".enabled,
    "splunk_last_updated: ".strftime(now(), "%x %T %Z")
    ))), "|"),
    nt_host=mvjoin(mvdedup(lower(mvappend(
    InstanceId,
    mvindex(split('NetworkInterfaces{}.Association.PublicDnsName',"."),0),
    mvindex(split('NetworkInterfaces{}.PrivateDnsName',"."),0),
    mvindex(split('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName',"."),0)
    ))), "|"),
    dns=mvjoin(lower(dns),"|"),
    priority="medium",
    ip=mvjoin('NetworkInterfaces{}.PrivateIpAddress', "|"),
    mac=mvjoin('NetworkInterfaces{}.MacAddress', "|"),
    _last_seen=now(),
    _key=md5(InstanceId)
| iplocation pub_ip_loc
| rename Country as country, City as city, lon as long
| table _key,_last_seen,ip,mac,nt_host,dns,priority,lat,long,city,country,category
```

**Comment by barrettnet** [comment]
The good news is that yes, the search works.  

The bad news is that I've just realised that the nt_host field is suffering the same sort of issue in that it's picking up the InstanceId - but not the other variations if they are multi-valued fields (which will be the case if the instance has multiple network interfaces).

My fix was to replace:
```
    mvindex(split('NetworkInterfaces{}.Association.PublicDnsName',"."),0),
    mvindex(split('NetworkInterfaces{}.PrivateDnsName',"."),0),
    mvindex(split('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName',"."),0)
```
with:
```
    mvmap('NetworkInterfaces{}.Association.PublicDnsName',replace('NetworkInterfaces{}.Association.PublicDnsName',"^([^\.]+)(?:.*?)$,"\1")),
    mvmap('NetworkInterfaces{}.PrivateDnsName',replace('NetworkInterfaces{}.PrivateDnsName',"^([^\.]+)(?:.*?)$,"\1")),
    mvmap('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName',replace('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName',"^([^\.]+)(?:.*?)$,"\1"))
```

In relation to the current search - the public_ip field is only used within the generation of the category field so it might be easier to remove this line:
`public_ip=mvjoin('NetworkInterfaces{}.Association.PublicIp', ","),`

and replace:
`"public_ip: ".public_ip,`

with:
`"public_ip: ".mvjoin('NetworkInterfaces{}.Association.PublicIp', ","),`

And should the delimiter used by the mvjoin be a comma followed by a space?  See for the tags subfield within the category field which uses a comma followed by a space as the delimiter.  I'm not sure what affect (if any) it makes with or within the space after the comma so it may just be a consistency thing.

Thank you for your support BTW.  It's much appreciated.

**Comment by ZachChristensen28** [comment]
Thanks for this! 

Out of curiosity, not that I am opposed to regex, but does the original logic of using mvindex work when you add mvmap?

```
    mvmap('NetworkInterfaces{}.Association.PublicDnsName', mvindex(split('NetworkInterfaces{}.Association.PublicDnsName',"."),0)),
    mvmap('NetworkInterfaces{}.PrivateDnsName', mvindex(split('NetworkInterfaces{}.PrivateDnsName',"."),0)),
    mvmap('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName', mvindex(split('NetworkInterfaces{}.PrivateIpAddresses{}.Association.PublicDnsName',"."),0))
```

**Comment by barrettnet** [comment]
Hi, yes, the mvindex/split method also works and, admittedly, looks a lot cleaner.
